### ISSUE TITLE
[Discuss] A race case when refresh token in multiple tabs

### ISSUE THREAD

**Issue by hiep294** [weareyipyip/multitab-token-refresh-js#7]
Suppose, there are two tabs, accessToken is shared between two tabs by localStorage.
+ At the same time, two tabs call an API route that requires authentication, but the accessToken has expired.
+ Two tabs run to refresh token, with the same refresh token: refreshTokenA
+ Tab 1 is served by API first => refreshTokenA cannot be used anymore
+ Tab 2 is served later, but it had already called API with refreshTokenA, so the API will throw an error to Tab 2
What do you think? Do you recommend a solution to solve the error in Tab2?

**Comment by juulSme** [comment]
Hi @hiep294, apologies for the very late response! We experience the same issue and have been looking into a solution. The current best thing we can do, which improves the situation, is what you find in #12, released as v2.0.2-beta. soon to be v2.0.2. There remains a problem, however, which is that LocalStorage itself is not synchronized between tabs in every browser (:eyes: firefox). This means that while the refresh may be synchronized correctly in v2, a second tab may still have a stale view of the storage state after a refresh. Based on our testing (=running with it for a while) this situation is rare, however. 

We have two strategies in mind for a "real" solution:
1. using indexeddb
1. using a service worker to store the tokens and intercept API requests

The first solution is relatively easy to implement but we simply haven't found the time yet. We would welcome PRs ;) The second solution would solve the problem and has the huge additional advantage of protecting token theft in case of an XSS vulnerability. It is unclear, however, if this lib would still play a role in such a solution, and if a generic service worker can be created to solve the problem, and if this is desirable in the first place given that there can be only one service worker per scope.
